server:
  port: 9001

spring:
  application:
    name: xiaofeng-consumer-9001

eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: xiaofeng-consumer-9001
    prefer-ip-address: true

logging:
  level:
    com:
      xiaofeng:
        blogs: debug