#server:
#  port: 80
##  port: 9527

feign:
  hystrix:
    enabled: true


#请求处理的超时时间
ribbon:
  ReadTimeout: 4000
#请求连接的超时时间
  ConnectTimeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
        timeout:
          enabled: false


spring:
  application:
    name: xiaofeng-consumer-80

eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: xiaofeng-consumer-80
    prefer-ip-address: true

zuul:
  sensitive-headers:  #设置请求头为空，否则会屏蔽cookie,导致session获取不到
  add-host-header: true
#  ignored-services: "*"
  routes: # 配置多个服务代理，给每个服务代理指定名称，然后配置相应的服务与路径
    dept-consumer:
      serviceId: xiaofeng-consumer-80
      path: /xiaofeng/**
    message-consumer:
      serviceId: xiaofeng-consumer-80
      path: /message/**
  host:
    connect-timeout-millis: 20000000
    socket-timeout-millis: 100000000



logging:
  level:
    com:
      xiaofeng:
        blogs: debug

---
server:
  port: 9527
spring:
  profiles: prod

---
server:
  port: 80
spring:
  profiles: dev